// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpZp8gomnT_J66tRyDFkucDfop78xijVI',
    appId: '1:528535337077:web:4533cc0dd2dd6e3bdca03c',
    messagingSenderId: '528535337077',
    projectId: 'yelle-bb06c',
    authDomain: 'yelle-bb06c.firebaseapp.com',
    storageBucket: 'yelle-bb06c.appspot.com',
    measurementId: 'G-FG1NGW5P5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuIkvVdCIDrKlRwSmkXRTXZq_IeFpg0G8',
    appId: '1:528535337077:android:95d318c8da442770dca03c',
    messagingSenderId: '528535337077',
    projectId: 'yelle-bb06c',
    storageBucket: 'yelle-bb06c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp2f1j6X8DQ7Pvv3Xn0TrtGHI8fFpzvxA',
    appId: '1:528535337077:ios:51c8e5d6a589eb43dca03c',
    messagingSenderId: '528535337077',
    projectId: 'yelle-bb06c',
    storageBucket: 'yelle-bb06c.appspot.com',
    iosBundleId: 'com.Studio385.Yelle',
  );
}
